services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
  # add your frontend service below

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
